var express = require('express')
var router = express()
var bodyParser = require('body-parser')
var port = require('./config/config-port.json')

/* router */
var internal = require('./gateway/internal/app')
var nutech = require('./gateway/nutech/app')
var btnpay = require('./gateway/btnpay/app')
var scf = require('./gateway/scf/app')
var branchforex = require('./gateway/branchforex/app')
var qris = require('./gateway/qris/app')
var ib = require('./gateway/ib/app')
var mid = require('./gateway/mid/app')
var mobilebanking = require('./gateway/mobilebanking/app')
var bankgaransi = require('./gateway/bankgaransi/app')
var pln = require('./gateway/pln/app')
var cms = require('./gateway/cms/app')
var pen = require('./gateway/pen/app')
var vascom = require('./gateway/vascom/app')
var edc = require('./gateway/edc/app')
var pemkotabalong = require('./gateway/pemko-tabalong/app')
var ewallet = require('./gateway/ewallet/app')

/* Body Parser */
router.use(bodyParser.json())
router.use(bodyParser.urlencoded({ extended: true }))

/* use Function */
router.use('/internal', internal)
router.use('/nutech', nutech)
router.use('/btnpay', btnpay)
router.use('/scf', scf)
router.use('/branchforex', branchforex)
router.use('/qris', qris)
router.use('/ib', ib)
router.use('/mid', mid)
router.use('/mobilebanking', mobilebanking)
router.use('/bankgaransi', bankgaransi)
router.use('/pln', pln)
router.use('/cms', cms)
router.use('/pen', pen)
router.use('/vascom', vascom)
router.use('/edc', edc)
router.use('/h2h-pemkotabalong', pemkotabalong)
router.use('/ewallet', ewallet)

console.log('The Gateway on port:' + port.gateway)
router.listen(port.gateway, '0.0.0.0')
